---

- name: Get list of all drivers
  win_command: driverquery /V
  changed_when: False
  register: driver_list

- name: Check if Red Hat certificate is not already installed
  win_shell: 'Get-ChildItem -Path Cert:\LocalMachine\TrustedPublisher'
  changed_when: False
  register: cert_check

- name: Install RH certificate
  block:
    - name: Export Cert from qxldod
      win_shell: '$cert = (Get-AuthenticodeSignature "{{ virtio_win_iso_path }}\qxldod\{{ virtio_driver_directory }}\amd64\qxldod.cat").SignerCertificate; [System.IO.File]::WriteAllBytes("{{ ansible_env.TEMP }}\redhat_qxldod.cer", $cert.Export([System.Security.Cryptography.X509Certificates.X509ContentType]::Cert));'

    - name: Export Cert from balloon
      win_shell: '$cert = (Get-AuthenticodeSignature "{{ virtio_win_iso_path }}\Balloon\{{ virtio_driver_directory }}\amd64\blnsvr.exe").SignerCertificate; [System.IO.File]::WriteAllBytes("{{ ansible_env.TEMP }}\redhat_balloon.cer", $cert.Export([System.Security.Cryptography.X509Certificates.X509ContentType]::Cert));'

    - name: Install RH certificate (qxldod) to TrustedPublisher certificate store
      win_command: 'certutil.exe -f -addstore "TrustedPublisher" {{ ansible_env.TEMP }}\redhat_qxldod.cer'

    - name: Install RH certificate (Balloon) to TrustedPublisher certificate store
      win_command: 'certutil.exe -f -addstore "TrustedPublisher" {{ ansible_env.TEMP }}\redhat_balloon.cer'

  when: cert_check.stdout is not search("Red Hat")

- name: Install the Virtio Network Driver (netkvm)
  win_command: "pnputil -i -a \"{{ virtio_win_iso_path }}\\NetKVM\\{{ virtio_driver_directory }}\\{{ ansible_env.PROCESSOR_ARCHITECTURE | lower }}\\*.inf\""
  when: driver_list.stdout is not search("netkvm")

- name: Install the Virtio Block Driver (viostor)
  win_command: "pnputil -i -a \"{{ virtio_win_iso_path }}\\viostor\\{{ virtio_driver_directory }}\\{{ ansible_env.PROCESSOR_ARCHITECTURE | lower }}\\*.inf\""
  when: driver_list.stdout is not search("viostor")

- name: Install the QXL Graphics Driver (qxldod)
  win_command: "pnputil -i -a \"{{ virtio_win_iso_path }}\\qxldod\\{{ virtio_driver_directory }}\\{{ ansible_env.PROCESSOR_ARCHITECTURE | lower }}\\*.inf\""
  when: driver_list.stdout is not search("qxldod")

- name: Install the Balloon Driver (Balloon)
  win_command: "pnputil -i -a \"{{ virtio_win_iso_path }}\\Balloon\\{{ virtio_driver_directory }}\\{{ ansible_env.PROCESSOR_ARCHITECTURE | lower }}\\*.inf\""
  when: driver_list.stdout is not search("balloon")

- name: Install Virtio RNG driver (viorng)
  win_command: "pnputil -i -a \"{{ virtio_win_iso_path }}\\viorng\\{{ virtio_driver_directory }}\\{{ ansible_env.PROCESSOR_ARCHITECTURE | lower }}\\*.inf\""
  when: driver_list.stdout is not search("viorng")

- name: Install Virtio serial driver (vioserial)
  win_command: "pnputil -i -a \"{{ virtio_win_iso_path }}\\vioserial\\{{ virtio_driver_directory }}\\{{ ansible_env.PROCESSOR_ARCHITECTURE | lower }}\\*.inf\""
  when: driver_list.stdout is not search("vioser")

- name: Install Virtio Input driver (vioinput)
  win_command: "pnputil -i -a \"{{ virtio_win_iso_path }}\\vioinput\\{{ virtio_driver_directory }}\\{{ ansible_env.PROCESSOR_ARCHITECTURE | lower }}\\*.inf\""
  when: driver_list.stdout is not search("vioinput")

# This wouldn't install, so skipping
- name: Install pvpanic device driver (pvpanic)
  win_command: "pnputil -i -a \"{{ virtio_win_iso_path }}\\pvpanic\\{{ virtio_driver_directory }}\\{{ ansible_env.PROCESSOR_ARCHITECTURE | lower }}\\*.inf\""
  when: False and driver_list.stdout is not search("pvpanic")

- name: Install Qemu Guest Agent (qemu-ga-x86_64.msi)
  win_package:
    path: "{{ virtio_win_iso_path }}\\guest-agent\\qemu-ga-x86_64.msi"
    creates_path: "{{ ansible_env['ProgramFiles'] }}\\qemu-ga"

- name: Delete certificates {{ ansible_env.SystemDrive }}\{redhat_balloon.cer,redhat_qxldod.cer}
  win_file:
    path: "{{ item }}"
    state: absent
  with_items:
    - "{{ ansible_env.TEMP }}\\redhat_balloon.cer"
    - "{{ ansible_env.TEMP }}\\redhat_qxldod.cer"
