---
- hosts: all
  vars:
    virtio_win_iso_path: 'D:\\virtio-win\\'
    virtio_driver_directory: w10

  tasks:
    - import_tasks: virtio-win.yml
      when: ansible_system_vendor == "QEMU"
    - import_tasks: vdagent-win.yml
      when: ansible_system_vendor == "QEMU"

    - name: Enable Administrator account
      win_user:
        name: Administrator
        account_disabled: no
      when: ansible_distribution is search("Microsoft Windows 10")

    - name: Remove all current pagefiles
      win_pagefile:
        remove_all: yes
        automatic: no
        state: absent

    - name: Disable Hibernate Mode
      win_command: powercfg -h off
      changed_when: false
      when: ansible_distribution is search("Microsoft Windows 10")
